## PROBLEM ASSIGNMENT 2

## 1. NORMALIZATION PROBLEM

In [23]:
import numpy as np

X = np.random.random((5,5))
X

M = X.mean()
M

STD = X.std()
STD

Z = (X-M)/STD
Z

np.save("X_normalized.npy", Z)

In [51]:
print ("\nNormal Array:\n\n", X)

print ("\nNormalized Array:\n\n", Z)


Normal Array:

 [[0.3622374  0.38353796 0.26403579 0.62881192 0.3862012 ]
 [0.86412915 0.90070498 0.79885762 0.54873955 0.29119705]
 [0.15426199 0.26970968 0.95160846 0.22218592 0.50845594]
 [0.94375162 0.72590956 0.22961087 0.2193884  0.40149975]
 [0.31316286 0.08937674 0.99102418 0.36834762 0.27554783]]

Normalized Array:

 [[-0.43881276 -0.36185418 -0.7936137   0.52431693 -0.35223192]
 [ 1.37451456  1.50666247  1.13868949  0.23501667 -0.6954805 ]
 [-1.1902248  -0.77311405  1.69057597 -0.94481667  0.08947262]
 [ 1.66218933  0.87512927 -0.91799043 -0.95492407 -0.2969585 ]
 [-0.61611834 -1.42465421  1.83298439 -0.41673666 -0.7520209 ]]


## 2. DIVISIBLE BY 3 PROBLEM 

In [46]:
import numpy as np

A = np.arange(1,101)
A

np.shape(A)

square = A.reshape(10,10)**2

divisible_by_3 = square[square%3 == 0]

np.save ("div_by_3.npy", divisible_by_3)

In [53]:
print ("\n10x10 Array: \n\n", square)

print ("\nNumbers Divisible by 3: \n\n",divisible_by_3)


10x10 Array: 

 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Numbers Divisible by 3: 

 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
