In [3]:
import numpy as np

In [6]:
X = np.random.random((5,5))
X

array([[0.62288828, 0.54479744, 0.82174396, 0.83464206, 0.29905298],
       [0.29925   , 0.75950722, 0.93259735, 0.32708512, 0.66348611],
       [0.30936796, 0.35276698, 0.36652808, 0.38347341, 0.45526209],
       [0.35435082, 0.64433915, 0.73397643, 0.38085071, 0.6789608 ],
       [0.56810517, 0.92007057, 0.18387639, 0.59375373, 0.65276748]])

In [7]:
M = X.mean()
M

np.float64(0.547340011198428)

In [8]:
STD= X.std()
STD

np.float64(0.21127859255208367)

In [9]:
Z = (X-M)/STD
Z

array([[ 0.35757653, -0.01203422,  1.2987778 ,  1.35982564, -1.17516418],
       [-1.17423166,  1.00420592,  1.82345659, -1.04248561,  0.54972962],
       [-1.12634246, -0.92093113, -0.85579865, -0.77559491, -0.43581284],
       [-0.91343467,  0.45910539,  0.88336644, -0.78800839,  0.62297268],
       [ 0.09828332,  1.76416624, -1.720305  ,  0.21968016,  0.49899739]])

In [10]:
np.save("X_normalized.nyp", Z)

In [12]:
print("Normal Array:\n", X)
print("Normalized Array:\n", Z)

Normal Array:
 [[0.62288828 0.54479744 0.82174396 0.83464206 0.29905298]
 [0.29925    0.75950722 0.93259735 0.32708512 0.66348611]
 [0.30936796 0.35276698 0.36652808 0.38347341 0.45526209]
 [0.35435082 0.64433915 0.73397643 0.38085071 0.6789608 ]
 [0.56810517 0.92007057 0.18387639 0.59375373 0.65276748]]
Normalized Array:
 [[ 0.35757653 -0.01203422  1.2987778   1.35982564 -1.17516418]
 [-1.17423166  1.00420592  1.82345659 -1.04248561  0.54972962]
 [-1.12634246 -0.92093113 -0.85579865 -0.77559491 -0.43581284]
 [-0.91343467  0.45910539  0.88336644 -0.78800839  0.62297268]
 [ 0.09828332  1.76416624 -1.720305    0.21968016  0.49899739]]
